/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puzzle;

/**
 *
 * @author Jorge Andres
 */
public class Puzzle extends javax.swing.JFrame {
    static int cont=1;
    /**
     * Creates new form Puzzle
     */
    public Puzzle() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Juego Puzzle");
        
        btn16.setVisible(false);
    }
    
    private void contarMovientos(){
        txtMovimientos.setText(String.valueOf(cont++));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMovimientos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn2 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("JUEGO PUZZLE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("Movimientos:");

        txtMovimientos.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txtMovimientos.setForeground(new java.awt.Color(255, 0, 0));
        txtMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMovimientosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMovimientos))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setLayout(new java.awt.GridLayout(4, 4));

        btn2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel3.add(btn2);

        btn10.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btn10.setText("10");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        jPanel3.add(btn10);

        btn6.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel3.add(btn6);

        btn12.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btn12.setText("12");
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        jPanel3.add(btn12);

        btn9.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel3.add(btn9);

        btn16.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btn16.setText("16");
        btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn16ActionPerformed(evt);
            }
        });
        jPanel3.add(btn16);

        btn14.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btn14.setText("14");
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });
        jPanel3.add(btn14);

        btn7.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel3.add(btn7);

        btn15.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btn15.setText("15");
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });
        jPanel3.add(btn15);

        btn8.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel3.add(btn8);

        btn4.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel3.add(btn4);

        btn11.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btn11.setText("11");
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        jPanel3.add(btn11);

        btn3.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel3.add(btn3);

        btn5.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel3.add(btn5);

        btn13.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btn13.setText("13");
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });
        jPanel3.add(btn13);

        btn1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if (btn9.isVisible()==false) {
            btn9.setText (btn2.getText () );
            btn9.setIcon(btn2.getIcon());
            btn2.setVisible(false);
            btn9.setVisible(true);
            contarMovientos();
        }
        if (btn10.isVisible()==false) {
            btn10.setText (btn2.getText () );
            btn10.setIcon(btn2.getIcon());
            btn2.setVisible(false);
            btn10.setVisible(true);
            contarMovientos();
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
        if (btn2.isVisible()==false) {
            btn2.setText (btn10.getText () );
            btn2.setIcon(btn10.getIcon());
            btn10.setVisible(false);
            btn2.setVisible(true);
            contarMovientos();
        }
        if (btn6.isVisible()==false) {
            btn6.setText (btn10.getText () );
            btn6.setIcon(btn10.getIcon());
            btn10.setVisible(false);
            btn6.setVisible(true);
            contarMovientos();
        }
        if (btn16.isVisible()==false) {
            btn16.setText (btn10.getText () );
            btn16.setIcon(btn10.getIcon());
            btn10.setVisible(false);
            btn16.setVisible(true);
            contarMovientos();
        }
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if (btn10.isVisible()==false) {
            btn10.setText (btn6.getText () );
            btn10.setIcon(btn6.getIcon());
            btn6.setVisible(false);
            btn10.setVisible(true);
            contarMovientos();
        }
        if (btn12.isVisible()==false) {
            btn12.setText (btn6.getText () );
            btn12.setIcon(btn6.getIcon());
            btn6.setVisible(false);
            btn12.setVisible(true);
            contarMovientos();
        }
        if (btn14.isVisible()==false) {
            btn14.setText (btn6.getText () );
            btn14.setIcon(btn6.getIcon());
            btn6.setVisible(false);
            btn14.setVisible(true);
            contarMovientos();
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
        if (btn6.isVisible()==false) {
            btn6.setText (btn12.getText () );
            btn6.setIcon(btn12.getIcon());
            btn12.setVisible(false);
            btn6.setVisible(true);
            contarMovientos();
        }
        if (btn7.isVisible()==false) {
            btn7.setText (btn12.getText () );
            btn7.setIcon(btn12.getIcon());
            btn12.setVisible(false);
            btn7.setVisible(true);
            contarMovientos();
        }
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if (btn2.isVisible()==false) {
            btn2.setText (btn9.getText () );
            btn2.setIcon(btn9.getIcon());
            btn9.setVisible(false);
            btn2.setVisible(true);
            contarMovientos();
        }
        if (btn15.isVisible()==false) {
            btn15.setText (btn9.getText () );
            btn15.setIcon(btn9.getIcon());
            btn9.setVisible(false);
            btn15.setVisible(true);
            contarMovientos();
        }
        if (btn16.isVisible()==false) {
            btn16.setText (btn9.getText () );
            btn16.setIcon(btn9.getIcon());
            btn9.setVisible(false);
            btn16.setVisible(true);
            contarMovientos();
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn16ActionPerformed
        // TODO add your handling code here:
        if (btn8.isVisible()==false) {
            btn8.setText (btn16.getText () );
            btn8.setIcon(btn16.getIcon());
            btn16.setVisible(false);
            btn8.setVisible(true);
            contarMovientos();
        }
        if (btn9.isVisible()==false) {
            btn9.setText (btn16.getText () );
            btn9.setIcon(btn16.getIcon());
            btn16.setVisible(false);
            btn9.setVisible(true);
            contarMovientos();
        }
        if (btn10.isVisible()==false) {
            btn10.setText (btn16.getText () );
            btn10.setIcon(btn16.getIcon());
            btn16.setVisible(false);
            btn10.setVisible(true);
            contarMovientos();
        }
        if (btn14.isVisible()==false) {
            btn14.setText (btn16.getText () );
            btn14.setIcon(btn16.getIcon());
            btn16.setVisible(false);
            btn14.setVisible(true);
            contarMovientos();
        }
    }//GEN-LAST:event_btn16ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        // TODO add your handling code here:
        if (btn4.isVisible()==false) {
            btn4.setText (btn14.getText () );
            btn4.setIcon(btn14.getIcon());
            btn14.setVisible(false);
            btn4.setVisible(true);
            contarMovientos();
        }
        if (btn6.isVisible()==false) {
            btn6.setText (btn14.getText () );
            btn6.setIcon(btn14.getIcon());
            btn14.setVisible(false);
            btn6.setVisible(true);
            contarMovientos();
        }
        if (btn7.isVisible()==false) {
            btn7.setText (btn14.getText () );
            btn7.setIcon(btn14.getIcon());
            btn14.setVisible(false);
            btn7.setVisible(true);
            contarMovientos();
        }
        if (btn16.isVisible()==false) {
            btn16.setText (btn14.getText () );
            btn16.setIcon(btn14.getIcon());
            btn14.setVisible(false);
            btn16.setVisible(true);
            contarMovientos();
        }
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if (btn11.isVisible()==false) {
            btn11.setText (btn7.getText () );
            btn11.setIcon(btn7.getIcon());
            btn7.setVisible(false);
            btn11.setVisible(true);
            contarMovientos();
        }
        if (btn12.isVisible()==false) {
            btn12.setText (btn7.getText () );
            btn12.setIcon(btn7.getIcon());
            btn7.setVisible(false);
            btn12.setVisible(true);
            contarMovientos();
        }
        if (btn14.isVisible()==false) {
            btn14.setText (btn7.getText () );
            btn14.setIcon(btn7.getIcon());
            btn7.setVisible(false);
            btn14.setVisible(true);
            contarMovientos();
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        // TODO add your handling code here:
        if (btn3.isVisible()==false) {
            btn3.setText (btn15.getText () );
            btn3.setIcon(btn15.getIcon());
            btn15.setVisible(false);
            btn3.setVisible(true);
            contarMovientos();
        }
        if (btn8.isVisible()==false) {
            btn8.setText (btn15.getText () );
            btn8.setIcon(btn15.getIcon());
            btn15.setVisible(false);
            btn8.setVisible(true);
            contarMovientos();
        }
        if (btn9.isVisible()==false) {
            btn9.setText (btn15.getText () );
            btn9.setIcon(btn15.getIcon());
            btn15.setVisible(false);
            btn9.setVisible(true);
            contarMovientos();
        }
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if (btn4.isVisible()==false) {
            btn4.setText (btn8.getText () );
            btn4.setIcon(btn8.getIcon());
            btn8.setVisible(false);
            btn4.setVisible(true);
            contarMovientos();
        }
        if (btn5.isVisible()==false) {
            btn5.setText (btn8.getText () );
            btn5.setIcon(btn8.getIcon());
            btn8.setVisible(false);
            btn5.setVisible(true);
            contarMovientos();
        }
        if (btn15.isVisible()==false) {
            btn15.setText (btn8.getText () );
            btn15.setIcon(btn8.getIcon());
            btn8.setVisible(false);
            btn15.setVisible(true);
            contarMovientos();
        }
        if (btn16.isVisible()==false) {
            btn16.setText (btn8.getText () );
            btn16.setIcon(btn8.getIcon());
            btn8.setVisible(false);
            btn16.setVisible(true);
            contarMovientos();
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if (btn8.isVisible()==false) {
            btn8.setText (btn4.getText () );
            btn8.setIcon(btn4.getIcon());
            btn4.setVisible(false);
            btn8.setVisible(true);
            contarMovientos();
        }
        if (btn11.isVisible()==false) {
            btn11.setText (btn4.getText () );
            btn11.setIcon(btn4.getIcon());
            btn4.setVisible(false);
            btn11.setVisible(true);
            contarMovientos();
        }
        if (btn13.isVisible()==false) {
            btn13.setText (btn4.getText () );
            btn13.setIcon(btn4.getIcon());
            btn4.setVisible(false);
            btn13.setVisible(true);
            contarMovientos();
        }
        if (btn14.isVisible()==false) {
            btn14.setText (btn4.getText () );
            btn14.setIcon(btn4.getIcon());
            btn4.setVisible(false);
            btn14.setVisible(true);
            contarMovientos();
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        // TODO add your handling code here:
        if (btn1.isVisible()==false) {
            btn1.setText (btn11.getText () );
            btn1.setIcon(btn11.getIcon());
            btn11.setVisible(false);
            btn1.setVisible(true);
            contarMovientos();
        }
        if (btn4.isVisible()==false) {
            btn4.setText (btn11.getText () );
            btn4.setIcon(btn11.getIcon());
            btn11.setVisible(false);
            btn4.setVisible(true);
            contarMovientos();
        }
        if (btn7.isVisible()==false) {
            btn7.setText (btn11.getText () );
            btn7.setIcon(btn11.getIcon());
            btn11.setVisible(false);
            btn7.setVisible(true);
            contarMovientos();
        }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if (btn5.isVisible()==false) {
            btn5.setText (btn3.getText () );
            btn5.setIcon(btn3.getIcon());
            btn3.setVisible(false);
            btn5.setVisible(true);
            contarMovientos();
        }
        if (btn15.isVisible()==false) {
            btn15.setText (btn3.getText () );
            btn15.setIcon(btn3.getIcon());
            btn3.setVisible(false);
            btn15.setVisible(true);
            contarMovientos();
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if (btn3.isVisible()==false) {
            btn3.setText (btn5.getText () );
            btn3.setIcon(btn5.getIcon());
            btn5.setVisible(false);
            btn3.setVisible(true);
            contarMovientos();
        }
        if (btn8.isVisible()==false) {
            btn8.setText (btn5.getText () );
            btn8.setIcon(btn5.getIcon());
            btn5.setVisible(false);
            btn8.setVisible(true);
            contarMovientos();
        }
        if (btn13.isVisible()==false) {
            btn13.setText (btn5.getText () );
            btn13.setIcon(btn5.getIcon());
            btn5.setVisible(false);
            btn13.setVisible(true);
            contarMovientos();
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        // TODO add your handling code here:
        if (btn1.isVisible()==false) {
            btn1.setText (btn13.getText () );
            btn1.setIcon(btn13.getIcon());
            btn13.setVisible(false);
            btn1.setVisible(true);
            contarMovientos();
        }
        if (btn4.isVisible()==false) {
            btn4.setText (btn13.getText () );
            btn4.setIcon(btn13.getIcon());
            btn13.setVisible(false);
            btn4.setVisible(true);
            contarMovientos();
        }
        if (btn5.isVisible()==false) {
            btn5.setText (btn13.getText () );
            btn5.setIcon(btn13.getIcon());
            btn13.setVisible(false);
            btn5.setVisible(true);
            contarMovientos();
        }
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        if (btn11.isVisible()==false) {
            btn11.setText (btn1.getText () );
            btn11.setIcon(btn1.getIcon());
            btn1.setVisible(false);
            btn11.setVisible(true);
            contarMovientos();
        }
        if (btn13.isVisible()==false) {
            btn13.setText (btn1.getText () );
            btn13.setIcon(btn1.getIcon());
            btn1.setVisible(false);
            btn13.setVisible(true);
            contarMovientos();
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void txtMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMovimientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMovimientosActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtMovimientos;
    // End of variables declaration//GEN-END:variables
}
