package vista;
import modelo.Logica;
import java.io.*;
import javax.swing.*;
import javax.swing.table.*;
import java.sql.*;
import modelo.Logica.*;

public class modelo extends javax.swing.JFrame {
    static Connection conn=null;
    static Statement st=null;
    static ResultSet rs=null;
    static ResultSet rs1=null;
    static ResultSet rs2=null;
    boolean yaprogramado=false;
    DefaultTableModel dtm=new DefaultTableModel();
    
    public modelo() {
        initComponents();
        try
            {
                conn=Logica.Enlace(conn);
                rs2=Logica.Vermarcas(rs2);
                while(rs2.next())
            {
                cbomarca.addItem((String)rs2.getString(1));
            }
        }
     catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Error"+e.getMessage());
        }
        String Titulos[]={"Marca","Modelo","Año","Precio","Colore","Km/s","Tipo"};
        dtm.setColumnIdentifiers(Titulos);
        tbmodelo.setModel(dtm);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btnagregar = new javax.swing.JButton();
        btngrabar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btnver = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbomarca = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        rbrojo = new javax.swing.JRadioButton();
        rbnegro = new javax.swing.JRadioButton();
        rbblanco = new javax.swing.JRadioButton();
        rbmarron = new javax.swing.JRadioButton();
        rbgris = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        cbotipo = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txtaño = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtkm = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbmodelo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(7, 50, 253));
        jLabel1.setText("Autos Premier");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("DejaVu Serif", 2, 11)); // NOI18N
        jLabel3.setText("El placer sobre ruedas... ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 480, 10));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnagregar.setText("Agregar");
        jPanel2.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 80, 20));

        btngrabar.setText("Grabar");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });
        jPanel2.add(btngrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 20));

        btncancelar.setText("  Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 20));

        btneditar.setText("  Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        jPanel2.add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 470, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Modelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 2, 11), new java.awt.Color(4, 76, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Nimbus Roman No9 L", 3, 11)); // NOI18N
        jLabel6.setText("Código");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 50, -1));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 70, -1));

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 70, 20));

        btnver.setText("Ver Lista");
        btnver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverActionPerformed(evt);
            }
        });
        jPanel1.add(btnver, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 80, 20));

        jLabel7.setFont(new java.awt.Font("Nimbus Roman No9 L", 3, 11)); // NOI18N
        jLabel7.setText("Color");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 50, -1));

        cbomarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "... Elegir ..." }));
        jPanel1.add(cbomarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 90, -1));

        jLabel8.setFont(new java.awt.Font("Nimbus Roman No9 L", 3, 11)); // NOI18N
        jLabel8.setText("Marca");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 50, -1));

        grupo.add(rbrojo);
        rbrojo.setText("Rojo");
        jPanel1.add(rbrojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        grupo.add(rbnegro);
        rbnegro.setText("Negro");
        jPanel1.add(rbnegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        grupo.add(rbblanco);
        rbblanco.setText("Blanco");
        jPanel1.add(rbblanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        grupo.add(rbmarron);
        rbmarron.setText("Marrón");
        jPanel1.add(rbmarron, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        grupo.add(rbgris);
        rbgris.setText("Gris");
        jPanel1.add(rbgris, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Nimbus Roman No9 L", 3, 11)); // NOI18N
        jLabel9.setText("Tipo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 50, -1));

        cbotipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "... Elegir ..." }));
        jPanel1.add(cbotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 90, -1));

        jLabel10.setFont(new java.awt.Font("Nimbus Roman No9 L", 3, 11)); // NOI18N
        jLabel10.setText("Año");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 50, -1));
        jPanel1.add(txtaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 70, -1));

        jLabel11.setFont(new java.awt.Font("Nimbus Roman No9 L", 3, 11)); // NOI18N
        jLabel11.setText("Km/s");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 50, -1));
        jPanel1.add(txtkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 70, -1));

        jLabel12.setFont(new java.awt.Font("Nimbus Roman No9 L", 3, 11)); // NOI18N
        jLabel12.setText("Precio");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 50, -1));
        jPanel1.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 70, -1));

        jLabel13.setFont(new java.awt.Font("Nimbus Roman No9 L", 3, 11)); // NOI18N
        jLabel13.setText("Modelo");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 50, -1));
        jPanel1.add(txtmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 470, 200));

        tbmodelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbmodelo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 470, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed

        int resp;
        boolean haygrabacion=false;
        resp = JOptionPane.showConfirmDialog(null, "¿Desea Grabar el Registro?", "Pregunta", 0);
        if (resp == 0) {
try {
                conn = Logica.Enlace(conn);
                st = Logica.sta(st);
                rs = Logica.Enlmodelo(rs);
                String mar,mod,col,tip,a,k,pre;
                int idmar=0;
                mar=(String)cbomarca.getSelectedItem();
                rs1=Logica.ObtenerCodMarca(rs1, mar);
                if(rs1.next()) {
                    idmar=Integer.parseInt(rs1.getString(1));
                    haygrabacion=true;
                } else {
                    JOptionPane.showMessageDialog(null,"Seleccione una Marca");
                    haygrabacion=false;
                }
                
                mod=(String)txtmodelo.getText();

               /* if(rbrojo.isSelected()){
                col="Rojo";
                }
                if(rbnegro.isSelected()){
                col="Negro";
                }
                if(rbmarron.isSelected()){
                col="Marron";
                }
                if(rbgris.isSelected()){
                col="Gris";
                }
                if(rbblanco.isSelected()){
                col="Blanco";
                }*/
                col=(String)txtaño.getText();
                tip=(String)cbotipo.getSelectedItem();
                a=(String)txtaño.getText();
                k=(String)txtkm.getText();
                pre=(String)txtprecio.getText();

                if(haygrabacion && !yaprogramado) {
                         PreparedStatement graba=conn.prepareStatement("{call graba_modelo(?,?,?,?,?,?,?)}");
                         graba.setString(1, mod);
                         graba.setString(2, a);
                         graba.setInt(3, idmar);
                         graba.setString(4, pre);
                         graba.setString(5, col);
                         graba.setString(6, k);
                         graba.setString(7, tip);
                         graba.executeUpdate();

                         conn.close();

                         txtid.setEnabled(true);
                                            }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error en BD" + e.toString());
            }
        }                    // TODO add your handling code here:

    }//GEN-LAST:event_btngrabarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        int resp;
        resp=JOptionPane.showConfirmDialog(null,"¿Desea Cancelar el Proceso?","Pregunta", 0);
      /*  if(resp==0) {
            limpiar();
            txtcodigo.setEnabled(true);
            activabotones(true,false,false,false);
            cajastexto(false,false,false,false,false,false,false);
        }*/            // TODO add your handling code here:
}//GEN-LAST:event_btncancelarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
int resp;
        resp=JOptionPane.showConfirmDialog(null,"¿Desea Modificar los Datos?","Pregunta", 0);
        if (resp==0) {
            try {
                conn=Logica.Enlace(conn);
                st=Logica.sta(st);
                rs=Logica.Enlmodelo(rs);

                String mar,des,an,pre,col,vel,tip;
                int codmar=0;

                des=txtmodelo.getText();
                an=txtaño.getText();
                pre=txtprecio.getText();
                col=txtkm.getText();
                vel=txtkm.getText();
                tip=(String)cbotipo.getSelectedItem();;

                mar=(String)cbomarca.getSelectedItem();
                rs1=Logica.ObtenerCodMarca(rs1, mar);
                if(rs1.next())
                    codmar=Integer.parseInt(rs1.getString(1));

                
                PreparedStatement modifica=conn.prepareStatement("{call edita_mod(?,?,?,?,?,?,?)}");
                modifica.setInt(1, codmar);
                modifica.setString(2, des);
                modifica.setString(3, an);
                modifica.setString(4, pre);
                modifica.setString(5, col);
                modifica.setString(6, vel);
                modifica.setString(7, tip);
                modifica.executeUpdate();
                JOptionPane.showMessageDialog(null,"Datos modificados correctamente");
                conn.close();
                
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null,"Error en BD"+ e.toString());
            }}                         // TODO add your handling code here:
}//GEN-LAST:event_btneditarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        String b;
        if (btnagregar.isEnabled()) {
            try {
                conn=Logica.Enlace(conn);
                rs=Logica.Enlmodelo(rs);
                b=txtid.getText();
                boolean encuentra=false;
                String pos;
                while(rs.next()) {
                    if(b.equals(rs.getString(1))) {
                        cbomarca.setSelectedItem(rs.getString(1));
                        txtmodelo.setText((String)rs.getString(2));
                        txtaño.setText((String)rs.getString(3));
                        txtprecio.setText((String)rs.getString(4));
                        txtkm.setText((String)rs.getString(6));
                        cbotipo.setSelectedItem(rs.getString(7));
                        txtid.setEnabled(false);

                        encuentra=true;
                        break;
                    }
                }
                if(encuentra==false) {
                    txtid.setText("No existe");
                    txtid.requestFocus();
                }
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null,"Error BD"+ e.getMessage());
            }
        }        // TODO add your handling code here:
}//GEN-LAST:event_btnbuscarActionPerformed

    private void btnverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverActionPerformed
        try {
            int f, i;
            conn=Logica.Enlace(conn);
            rs=Logica.Enlmodelo(rs);
            String datos[]=new String[7];
            f=dtm.getRowCount();
            if(f>0)
                for(i=0;i<f;i++)
                    dtm.removeRow(0);
            while(rs.next()) {
                datos[0]=(String)rs.getString(1);
                datos[1]=(String)rs.getString(2);
                datos[2]=(String)rs.getString(3);
                datos[3]=(String)rs.getString(4);
                datos[4]=(String)rs.getString(5);
                datos[5]=(String)rs.getString(6);
                datos[6]=(String)rs.getString(7);
                
                dtm.addRow(datos);
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null,"Error en BD "+e.toString());
        }        // TODO add your handling code here:
}//GEN-LAST:event_btnverActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btnver;
    private javax.swing.JComboBox cbomarca;
    private javax.swing.JComboBox cbotipo;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbblanco;
    private javax.swing.JRadioButton rbgris;
    private javax.swing.JRadioButton rbmarron;
    private javax.swing.JRadioButton rbnegro;
    private javax.swing.JRadioButton rbrojo;
    private javax.swing.JTable tbmodelo;
    private javax.swing.JTextField txtaño;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtkm;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables

}
