package vista;
import modelo.Logica;
import java.io.*;
import javax.swing.*;
//import javax.swing.table.*;
import java.sql.*;
import modelo.Logica.*;

public class new_usuario extends javax.swing.JFrame {
    static Connection conn=null;
    static Statement st=null;
    static ResultSet rs=null;
  
    public new_usuario() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcontra = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        txtdir = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(7, 50, 253));
        jLabel1.setText("Autos Premier");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 310, 10));

        jLabel3.setFont(new java.awt.Font("DejaVu Serif", 2, 11)); // NOI18N
        jLabel3.setText("El placer sobre ruedas... ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 0, 12), new java.awt.Color(102, 102, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Identidad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel4.setText("Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));
        jPanel1.add(txtcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 130, -1));
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 440, 70));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 0, 12), new java.awt.Color(102, 102, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Nombres:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel10.setText("Apellidos:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel11.setText("Telefono:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel12.setText("DNI:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel14.setText("Dirección:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 130, -1));
        jPanel2.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 130, -1));
        jPanel2.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 130, -1));
        jPanel2.add(txtdir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 330, -1));
        jPanel2.add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 130, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 440, 240));

        btnagregar.setFont(new java.awt.Font("Nimbus Roman No9 L", 3, 13)); // NOI18N
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.gif"))); // NOI18N
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 40, 30));

        jButton1.setText("cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        int resp;
                                        resp = JOptionPane.showConfirmDialog(null, "¿Desea Grabar el Registro?", "Pregunta", 0);
                                        if (resp == 0) {
                                            try {
                                                conn = Logica.Enlace(conn);
                                                st = Logica.sta(st);
                                                rs = Logica.Enluser(rs);
                                                String nom,ape,dn,tel,dir,user,contra;
                                                nom = txtnombre.getText();
                                                ape = txtapellidos.getText();
                                                dn = txtdni.getText();
                                                tel = txttel.getText();
                                                dir = txtdir.getText();
                                                user = txtuser.getText();
                                                contra = txtcontra.getText();
                                                PreparedStatement graba = conn.prepareStatement("{call graba_user(?,?,?,?,?,?,?)}");

                                                graba.setString(1, nom);
                                                graba.setString(2, ape);
                                                graba.setString(3, dn);
                                                graba.setString(4, tel);
                                                graba.setString(5, dir);
                                                graba.setString(6, user);
                                                graba.setString(7, contra);
                                                graba.executeUpdate();
                                                JOptionPane.showMessageDialog(null,"Usuario Registrado correctamente");
                                                
                                                txtnombre.setText("");
                                                txtapellidos.setText("");
                                                txtdni.setText("");
                                                txttel.setText("");
                                                txtdir.setText("");
                                                txtuser.setText("");                                                
                                                txtcontra.setText("");
                                                txtnombre.requestFocus();
                                                dispose();
                                                conn.close();
                                                
                                            } catch (SQLException e) {
                                                JOptionPane.showMessageDialog(null, "Error en BD" + e.toString());
                                            }
                                        }
}//GEN-LAST:event_btnagregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcontra;
    private javax.swing.JTextField txtdir;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables

}
