package vista;

import modelo.rep_cliente;
import modelo.Logica;
import javax.swing.*;
import java.sql.*;
import modelo.Logica.*;
import javax.swing.table.*;
import java.util.Date;
import java.awt.event.KeyEvent;

public class principal extends javax.swing.JFrame {
    static Connection conn=null;
    static Statement st=null;
    static ResultSet rs=null;
    static ResultSet rs1=null;
    static ResultSet rs2=null;
    static ResultSet rs3=null;
    static ResultSet rs4=null;
    boolean yaprogramado=false;
        DefaultTableModel dtm=new DefaultTableModel();
        DefaultTableModel rep=new DefaultTableModel();
        DefaultListModel l1=new DefaultListModel();
    DefaultListModel l2=new DefaultListModel();
    DefaultListModel l3=new DefaultListModel();
    DefaultListModel l4=new DefaultListModel();
    DefaultListModel l5=new DefaultListModel();
    DefaultListModel l6=new DefaultListModel();
    public principal() {
        initComponents();

        //cliente
        String Titulos[]={"DNI","Cliente","Direccion","Telefono"};
        dtm.setColumnIdentifiers(Titulos);
        tbcliente.setModel(dtm);
        //repuesto
        String repu[]={"Nombre","Descripcion","Precio","Stock"};
        rep.setColumnIdentifiers(repu);
        tbrep.setModel(rep);
        txtruc1.setVisible(false);
        lbruc1.setVisible(false);
        
        //hora
         //modelo.tiempo re=new modelo.tiempo(lbhora);
         tiempo re;
    re = new tiempo(lbhora);
    re.start();
//fecha
    Date d=new Date();
    String fecha=((d.getYear()+1900)+"-"+(d.getMonth()+1)+"-"+d.getDate());
 lbfecha.setText(fecha);
//fin fecha
        txtruc.setVisible(false);
        lbruc.setVisible(false);
        try //combo marcas
            {
                conn=Logica.Enlace(conn);
                rs1=Logica.Vermarcas(rs);
                while(rs1.next())
            {
                cbomarca.addItem((String)rs1.getString(1));
            }
        }
     catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Error"+e.getMessage());
        }
          try{ //combo clientes
            conn=Logica.Enlace(conn);
            rs=Logica.Enlcliente(rs);
            while(rs.next())
             cbocliente.addItem(rs.getString(4));
             rs.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error en Bd"+ e.getMessage());
        }

         try{
            conn=Logica.Enlace(conn);
            rs=Logica.Enlcliente(rs);
            while(rs.next())
             cboclienterep.addItem(rs.getString(4));
             rs.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error en Bd"+ e.getMessage());
        }

         try{ //combo productos
            conn=Logica.Enlace(conn);
            rs=Logica.Enlrepuesto(rs);
            while(rs.next())
             cborep.addItem(rs.getString(2));
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error en Bd"+ e.getMessage());
        }
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbfecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbhora = new javax.swing.JLabel();
        auto = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtcan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbomarca = new javax.swing.JComboBox();
        cbocolor = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        btnmodelo1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cbomodelo = new javax.swing.JComboBox();
        cbotipo = new javax.swing.JComboBox();
        lbtotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbprecio = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbocliente = new javax.swing.JComboBox();
        btngrabar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        lbruc = new javax.swing.JLabel();
        cboxcomprobante = new javax.swing.JComboBox();
        txtruc = new javax.swing.JTextField();
        cliente = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        txtdir = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btnver = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnagregar = new javax.swing.JButton();
        btngrabar1 = new javax.swing.JButton();
        btncancelar1 = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcliente = new javax.swing.JTable();
        repuestos = new javax.swing.JInternalFrame();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtst = new javax.swing.JTextField();
        txtpre = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtnrep = new javax.swing.JTextField();
        busrep = new javax.swing.JButton();
        verrep = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtdes = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        btnagregar1 = new javax.swing.JButton();
        grabrep = new javax.swing.JButton();
        btncancelar2 = new javax.swing.JButton();
        editrep = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbrep = new javax.swing.JTable();
        vrep = new javax.swing.JInternalFrame();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        cborep = new javax.swing.JComboBox();
        lbinf = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtcanrep = new javax.swing.JTextField();
        lbprerep = new javax.swing.JLabel();
        txttotrep = new javax.swing.JTextField();
        totrep = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        cboclienterep = new javax.swing.JComboBox();
        btngrabarrep = new javax.swing.JButton();
        btncancelar3 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        lbruc1 = new javax.swing.JLabel();
        cboxcomprobante1 = new javax.swing.JComboBox();
        txtruc1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lbfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 20));

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(7, 50, 253));
        jLabel1.setText("Autos Premier");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 480, 10));

        jLabel3.setFont(new java.awt.Font("DejaVu Serif", 2, 11)); // NOI18N
        jLabel3.setText("El placer sobre ruedas... ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel10.setText("Hora");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));
        getContentPane().add(lbhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 80, 20));

        auto.setClosable(true);
        auto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Venta de Autos"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 2, 11), new java.awt.Color(4, 76, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Nimbus Roman No9 L", 3, 11)); // NOI18N
        jLabel5.setText("Cantidad");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 60, -1));
        jPanel3.add(txtcan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 80, 20));

        jLabel11.setFont(new java.awt.Font("Nimbus Roman No9 L", 3, 11)); // NOI18N
        jLabel11.setText("Color:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 50, -1));

        cbomarca.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        cbomarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "... Elegir ..." }));
        cbomarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbomarcaActionPerformed(evt);
            }
        });
        jPanel3.add(cbomarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 100, 20));

        cbocolor.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        cbocolor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "... Elegir ...", "Rojo", "Verde", "Blanco", "Gris", "Negro" }));
        cbocolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbocolorActionPerformed(evt);
            }
        });
        jPanel3.add(cbocolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 100, 20));

        jLabel8.setFont(new java.awt.Font("Nimbus Roman No9 L", 3, 11)); // NOI18N
        jLabel8.setText("Marca");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 50, -1));

        btnmodelo1.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        btnmodelo1.setText("Ver Modelos");
        btnmodelo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodelo1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnmodelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 100, 20));

        jLabel12.setFont(new java.awt.Font("Nimbus Roman No9 L", 3, 11)); // NOI18N
        jLabel12.setText("Tipo:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 50, -1));

        cbomodelo.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        cbomodelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "... Elegir ..." }));
        cbomodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbomodeloActionPerformed(evt);
            }
        });
        jPanel3.add(cbomodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 100, 20));

        cbotipo.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        cbotipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "... Elegir ...", "Camioneta", "Auto", "Todo Terreno" }));
        cbotipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbotipoActionPerformed(evt);
            }
        });
        jPanel3.add(cbotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 100, 20));
        jPanel3.add(lbtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 60, 20));

        jButton1.setText("A pagar !!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, 20));

        lbprecio.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        jPanel3.add(lbprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 250, 20));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 610, 190));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 2, 11), new java.awt.Color(4, 76, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbocliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar" }));
        jPanel1.add(cbocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 200, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 560, 90));

        btngrabar.setText("Grabar");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });
        jPanel2.add(btngrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, 20));

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, 20));

        auto.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 720, 400));

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Comprobante"));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbruc.setText("Ruc: ");
        jPanel13.add(lbruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        cboxcomprobante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Factura", "Boleta" }));
        cboxcomprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxcomprobanteActionPerformed(evt);
            }
        });
        jPanel13.add(cboxcomprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 130, 20));
        jPanel13.add(txtruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 130, -1));

        auto.getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 240, 90));

        getContentPane().add(auto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 740, 580));

        cliente.setClosable(true);
        cliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Venta de Autos"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 0, 12), new java.awt.Color(102, 102, 255))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Nombres:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel13.setText("Apellidos:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel14.setText("Telefono:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel15.setText("Dirección:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        jPanel5.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 130, -1));
        jPanel5.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 130, -1));
        jPanel5.add(txtdir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 330, -1));
        jPanel5.add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 130, -1));

        jLabel16.setText("DNI:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel5.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 130, -1));

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel5.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 70, 20));

        btnver.setText("Ver Lista");
        btnver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverActionPerformed(evt);
            }
        });
        jPanel5.add(btnver, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 80, 20));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 440, 160));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnagregar.setText("Agregar");
        jPanel6.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 80, 20));

        btngrabar1.setText("Grabar");
        btngrabar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabar1ActionPerformed(evt);
            }
        });
        jPanel6.add(btngrabar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 20));

        btncancelar1.setText("  Cancelar");
        btncancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar1ActionPerformed(evt);
            }
        });
        jPanel6.add(btncancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 20));

        btneditar.setText("  Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        jPanel6.add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 20));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 470, 40));

        tbcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbcliente);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, 110));

        cliente.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 700, 370));

        getContentPane().add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 740, 450));

        repuestos.setClosable(true);
        repuestos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Repuestos"));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 0, 12), new java.awt.Color(102, 102, 255))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Descripcion:");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel19.setText("Precio:");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel20.setText("Stock:");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));
        jPanel8.add(txtst, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 50, -1));
        jPanel8.add(txtpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 50, -1));

        jLabel21.setText("Nombre:");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel8.add(txtnrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 130, -1));

        busrep.setText("Buscar");
        busrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busrepActionPerformed(evt);
            }
        });
        jPanel8.add(busrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 70, 20));

        verrep.setText("Ver Lista");
        verrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verrepActionPerformed(evt);
            }
        });
        jPanel8.add(verrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 80, 20));

        txtdes.setColumns(20);
        txtdes.setRows(5);
        jScrollPane3.setViewportView(txtdes);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 220, 110));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 510, 180));

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnagregar1.setText("Agregar");
        jPanel9.add(btnagregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 80, 20));

        grabrep.setText("Grabar");
        grabrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabrepActionPerformed(evt);
            }
        });
        jPanel9.add(grabrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 20));

        btncancelar2.setText("  Cancelar");
        btncancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar2ActionPerformed(evt);
            }
        });
        jPanel9.add(btncancelar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 20));

        editrep.setText("  Editar");
        editrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editrepActionPerformed(evt);
            }
        });
        jPanel9.add(editrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 20));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 470, 40));

        tbrep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbrep);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, 110));

        repuestos.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 700, 390));

        getContentPane().add(repuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 740, 450));

        vrep.setClosable(true);
        vrep.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Venta de Repuestos"));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 2, 11), new java.awt.Color(4, 76, 255))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Nimbus Roman No9 L", 3, 11)); // NOI18N
        jLabel22.setText("Cantidad");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 60, -1));

        cborep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...Elegir..." }));
        cborep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cborepActionPerformed(evt);
            }
        });
        jPanel11.add(cborep, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 100, -1));
        jPanel11.add(lbinf, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 320, 100));

        jLabel23.setFont(new java.awt.Font("Nimbus Roman No9 L", 3, 11)); // NOI18N
        jLabel23.setText("Repuestos");
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 60, -1));
        jPanel11.add(txtcanrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 100, -1));
        jPanel11.add(lbprerep, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 90, 30));
        jPanel11.add(txttotrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 100, -1));

        totrep.setText("Total a pagar");
        totrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totrepActionPerformed(evt);
            }
        });
        jPanel11.add(totrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 690, 210));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 2, 11), new java.awt.Color(4, 76, 255))); // NOI18N
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboclienterep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar" }));
        jPanel12.add(cboclienterep, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 200, -1));

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 560, 60));

        btngrabarrep.setText("Grabar");
        btngrabarrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarrepActionPerformed(evt);
            }
        });
        jPanel10.add(btngrabarrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, 20));

        btncancelar3.setText("Cancelar");
        btncancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar3ActionPerformed(evt);
            }
        });
        jPanel10.add(btncancelar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, 20));

        vrep.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 710, 350));

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Comprobante"));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbruc1.setText("Ruc: ");
        jPanel14.add(lbruc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        cboxcomprobante1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Factura", "Boleta" }));
        cboxcomprobante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxcomprobante1ActionPerformed(evt);
            }
        });
        jPanel14.add(cboxcomprobante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 130, 20));
        jPanel14.add(txtruc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 130, -1));

        vrep.getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 240, 90));

        getContentPane().add(vrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 740, 450));

        jMenu1.setText("Tareas");

        jMenuItem1.setText("Venta Auto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Venta Repuestos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem6.setText("Agregar Repuestos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cliente");

        jMenuItem3.setText("Datos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Reportes");

        jMenuItem4.setText("Ventas de autos al mes");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Ventas de Repuestos al mes");
        jMenu3.add(jMenuItem5);

        jMenuItem7.setText("cliente");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxcomprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxcomprobanteActionPerformed
        String compara;
        
            compara=(String)cboxcomprobante.getSelectedItem();
            if(compara.equals("Boleta")){
                txtruc.setVisible(false);
                lbruc.setVisible(false);
            }
            if(compara.equals("Factura")){
                txtruc.setVisible(true);
                lbruc.setVisible(true);
                txtruc.requestFocus();

            }
            if(compara.equals("Seleccionar")){
                txtruc.setVisible(false);
                lbruc.setVisible(false);
            }
            
}//GEN-LAST:event_cboxcomprobanteActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
       /* l1.removeAllElements();
        l2.removeAllElements();
        l3.removeAllElements();
        l4.removeAllElements();
        txtcantidad.setText("");
        txtprobuscar.setText("");
        l5.removeAllElements();
        l6.removeAllElements();
        txttotalpagar.setText("");
        botonesagregar(false,false);
        botonesagregar(false,false);
        cajastexto(false,false,false,false,false,false,false);
        activabotones(true,false,false,false);
        txtcliente.setText("");
        cbocliente.setSelectedIndex(0);
        txtruc.setText("");
        rbtnnuevo.setSelected(false);
        rbtnregistrado.setSelected(false);*/
}//GEN-LAST:event_btncancelarActionPerformed

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        int resp;
        boolean haygrabacion=false;
        resp=JOptionPane.showConfirmDialog(null,"¿Desea Grabar la venta actual?","Pregunta",0);
        if(resp==0) {
            try {
                conn=Logica.Enlace(conn);
                st=Logica.sta(st);
                rs=Logica.Enlvautos(rs);

                String mar,mod,compr,ruc,tip,col,cant,total,cliente_n,fecha,hora,cregistrado;
                int cod,codmar=0,codmod=0,codcli=0;

                mar=(String)cbomarca.getSelectedItem();
                rs1=Logica.ObtenerCodMarca(rs1, mar);
                if(rs1.next()) {
                    codmar=Integer.parseInt((String)rs1.getString(1));
                    haygrabacion=true;
                } else {
                    JOptionPane.showMessageDialog(null,"Seleccione una marca");
                    haygrabacion=false;
                }

                mod=(String)cbomodelo.getSelectedItem();
                rs2=Logica.ObtenerCodModelo(rs2, mod);
                if(rs2.next()) {
                    codmod=Integer.parseInt((String)rs2.getString(1));
                    haygrabacion=true;
                } else {
                    JOptionPane.showMessageDialog(null,"Seleccione un Modelo");
                    haygrabacion=false;
                }

                mod=(String)cbocliente.getSelectedItem();
                rs3=Logica.ObtenerCodcliente(rs3, mod);
                if(rs3.next()) {
                    codcli=Integer.parseInt((String)rs3.getString(1));
                    haygrabacion=true;
                } else {
                    JOptionPane.showMessageDialog(null,"Seleccione un Cliente");
                    haygrabacion=false;
                }


                compr=(String)cboxcomprobante.getSelectedItem();
                ruc=txtruc.getText();
                tip=(String)cbotipo.getSelectedItem();
                col=(String)cbocolor.getSelectedItem();
                cant=txtcan.getText();
                hora=lbhora.getText();
                fecha=lbfecha.getText();
                total=lbtotal.getText();
                //cregistrado=(String)cbocliente.getSelectedItem();



                if(((String)cboxcomprobante.getSelectedItem()).equals("Seleccionar")){
                    JOptionPane.showMessageDialog(null,"Seleccione un Comprobante");
                    cboxcomprobante.requestFocus();
                }else{
                    if(((String)cbomarca.getSelectedItem()).equals("...Elegir...")){
                        JOptionPane.showMessageDialog(null,"Seleccione una marca");
                        cbomarca.requestFocus();
                    }else{
                        if(((String)cbotipo.getSelectedItem()).equals("...Elegir...")){
                            JOptionPane.showMessageDialog(null,"Seleccione un tipo de Auto");
                            cbotipo.requestFocus();
                        }else{

                            if(((String)cbocolor.getSelectedItem()).equals("...Elegir...")){
                                JOptionPane.showMessageDialog(null,"Seleccione un color");
                                cbocolor.requestFocus();
                            }else{
                                if(((String)cbomodelo.getSelectedItem()).equals("...Elegir...")){
                                    JOptionPane.showMessageDialog(null,"Seleccione un tipo de Modelo");
                                    cbomodelo.requestFocus();
                                }else{
                                    if(ruc.equals("")){
                                        JOptionPane.showMessageDialog(null,"Ingrese su numero de RUC");
                                        txtruc.requestFocus();
                                    }else{

                                        if(cant.equals("")){
                                            JOptionPane.showMessageDialog(null,"Ingrese una cantidad determinada");
                                            txtruc.requestFocus();
                                        }else{
                                            if(haygrabacion && !yaprogramado) {
                                                PreparedStatement graba=conn.prepareStatement("{call graba_v_auto(?,?,?,?,?,?,?,?,?,?,?)}");
                                                graba.setInt(1, codcli);
                                                graba.setInt(2, codmar);
                                                graba.setInt(3, codmod);
                                                graba.setString(4, compr);
                                                graba.setString(5, ruc);
                                                graba.setString(6, tip);
                                                graba.setString(7, col);
                                                graba.setString(8, cant);
                                                graba.setString(9, total);
                                                graba.setString(10, fecha);
                                                graba.setString(11, hora);
                                                graba.executeUpdate();
                                                JOptionPane.showMessageDialog(null,"Datos de venta registrados con éxito");
                                                conn.close();
                                                //activabotones(true,false,false,false);
                                                //limpiar()
                                            }}}}}}}}
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null,"Error en BD"+e.toString());
            }
        }
}//GEN-LAST:event_btngrabarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String mod;

        try{
            String res;
            int total,a,b,pre=0;
            mod=(String)cbomodelo.getSelectedItem();
            rs4=Logica.precio(rs4, mod);
            if(rs4.next())
                pre=Integer.parseInt(rs4.getString(1));

            a=Integer.parseInt(txtcan.getText());
            total=a * pre;
            res=String.valueOf(total);
            lbtotal.setText(res);
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(null,"Error en BD"+e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbotipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbotipoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cbotipoActionPerformed

    private void cbomodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbomodeloActionPerformed
        // TODO add your handling code here:
        String mod;

        try{
            int pre=0;
            mod=(String)cbomodelo.getSelectedItem();
            rs4=Logica.precio(rs4, mod);
            if(rs4.next())
                pre=Integer.parseInt(rs4.getString(1));
            lbprecio.setText("El precio de dicho modelo es de:"+ String.valueOf(pre));
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(null,"Error en BD"+e.toString());
        }
}//GEN-LAST:event_cbomodeloActionPerformed

    private void btnmodelo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodelo1ActionPerformed

        // TODO add your handling code here:
        String mar;
        mar=(String)cbomarca.getSelectedItem();
        try {
            conn=Logica.Enlace(conn);
            rs=Logica.Vermodelos(rs, mar);

            while(rs.next()) {
                cbomodelo.addItem((String)rs.getString(1));

                this.setSize(580,400);
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Error"+e.getMessage());
        }
}//GEN-LAST:event_btnmodelo1ActionPerformed

    private void cbocolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbocolorActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cbocolorActionPerformed

    private void cbomarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbomarcaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cbomarcaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        auto.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        String b;
        if (btnagregar.isEnabled()) {
            try {
                conn=Logica.Enlace(conn);
                rs=Logica.Enlcliente(rs);
                b=txtdni.getText();
                boolean encuentra=false;
                String pos;
                while(rs.next()) {
                    if(b.equals(rs.getString(2))) {
                        txtnombre.setText((String)rs.getString(3));
                        txtapellidos.setText((String)rs.getString(4));
                        txtdir.setText((String)rs.getString(5));
                        txttel.setText((String)rs.getString(6));
                        encuentra=true;
                        break;
                    }
                }
                if(encuentra==false) {
                    txtdni.setText("No existe");
                    txtdni.requestFocus();
                }
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null,"Error BD"+ e.getMessage());
            }
        }        // TODO add your handling code here:
}//GEN-LAST:event_btnbuscarActionPerformed

    private void btnverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverActionPerformed
        try {
            int f, i;
            conn=Logica.Enlace(conn);
            rs=Logica.Enlcliente(rs);
            String datos[]=new String[5];
            f=dtm.getRowCount();
            if(f>0)
                for(i=0;i<f;i++)
                    dtm.removeRow(0);
            while(rs.next()) {
                datos[0]=(String)rs.getString(2);
                datos[1]=(String)rs.getString(3)+' '+(String)rs.getString(4);
                datos[2]=(String)rs.getString(5);
                datos[3]=(String)rs.getString(6);
                dtm.addRow(datos);
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null,"Error en BD "+e.toString());
        }        // TODO add your handling code here:
}//GEN-LAST:event_btnverActionPerformed

    private void btngrabar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabar1ActionPerformed


        int resp;
        resp = JOptionPane.showConfirmDialog(null, "¿Desea Grabar el Registro?", "Pregunta", 0);
        if (resp == 0) {
            try {
                conn = Logica.Enlace(conn);
                st = Logica.sta(st);
                rs = Logica.Enlcliente(rs);
                String nom,ape,dni,dir,tel;
                nom = txtnombre.getText();
                ape = txtapellidos.getText();
                dni = txtdni.getText();
                dir = txtdir.getText();
                tel = txttel.getText();
                PreparedStatement graba = conn.prepareStatement("{call graba_cliente(?,?,?,?,?)}");

                graba.setString(1, dni);
                graba.setString(2, nom);
                graba.setString(3, ape);
                graba.setString(4, dir);
                graba.setString(5, tel);
                graba.executeUpdate();
                JOptionPane.showMessageDialog(null, "Cliente registrado con Exito");
                conn.close();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error en BD" + e.toString());
            }
        }                    // TODO add your handling code here:
    }//GEN-LAST:event_btngrabar1ActionPerformed

    private void btncancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar1ActionPerformed
        int resp;
        resp=JOptionPane.showConfirmDialog(null,"¿Desea Cancelar el Proceso?","Pregunta", 0);
      /* if(resp==0) {
            limpiar();
            txtcodigo.setEnabled(true);
            activabotones(true,false,false,false);
            cajastexto(false,false,false,false,false,false,false);
        }*/            // TODO add your handling code here:
}//GEN-LAST:event_btncancelar1ActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        int resp;
        resp=JOptionPane.showConfirmDialog(null,"¿Desea Modificar los Datos?","Pregunta", 0);
        if (resp==0) {
            try {
                conn=Logica.Enlace(conn);
                st=Logica.sta(st);
                rs=Logica.Enlcliente(rs);

                String  nom,ape,dni,dir,tel;

                dni=txtdni.getText();
                nom=txtnombre.getText();
                ape=txtapellidos.getText();
                dir=txtdir.getText();
                tel=txttel.getText();

                PreparedStatement modifica=conn.prepareStatement("{call edita_cliente(?,?,?,?,?)}");

                modifica.setString(1, dni);
                modifica.setString(2, nom);
                modifica.setString(3, ape);
                modifica.setString(4, dir);
                modifica.setString(5, tel);

                modifica.executeUpdate();
                JOptionPane.showMessageDialog(null, "Datos modificados con Exito");
                conn.close();

            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null,"Error en BD"+ e.toString());
            }}                      // TODO add your handling code here:
}//GEN-LAST:event_btneditarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        cliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void busrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busrepActionPerformed
        // TODO add your handling code here:
        String b;
        if (btnagregar.isEnabled()) {
            try {
                conn=Logica.Enlace(conn);
                rs=Logica.Enlrepuesto(rs);
                b=txtnrep.getText();
                boolean encuentra=false;
                String pos;
                while(rs.next()) {
                    if(b.equals(rs.getString(2))) {

                        txtdes.setText((String)rs.getString(3));
                        txtpre.setText((String)rs.getString(4));
                        txtst.setText((String)rs.getString(5));
                        encuentra=true;
                        break;
                    }
                }
                if(encuentra==false) {
                    txtnrep.setText("No existe");
                    txtnrep.requestFocus();
                }
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null,"Error BD"+ e.getMessage());
            }
        }
    }//GEN-LAST:event_busrepActionPerformed

    private void verrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verrepActionPerformed
        // TODO add your handling code here:
        try {
            int f, i;
            conn=Logica.Enlace(conn);
            rs=Logica.Enlrepuesto(rs);
            String repuesto[]=new String[4];
            f=rep.getRowCount();
            if(f>0)
                for(i=0;i<f;i++)
                    rep.removeRow(0);
            while(rs.next()) {
                repuesto[0]=(String)rs.getString(2);
                repuesto[1]=(String)rs.getString(3);
                repuesto[2]=(String)rs.getString(4);
                repuesto[3]=(String)rs.getString(5);
                rep.addRow(repuesto);
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null,"Error en BD "+e.toString());
        }
    }//GEN-LAST:event_verrepActionPerformed

    private void grabrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabrepActionPerformed
        // TODO add your handling code here:
        int resp;
        resp = JOptionPane.showConfirmDialog(null, "¿Desea Grabar el Registro?", "Pregunta", 0);
        if (resp == 0) {
            try {
                conn = Logica.Enlace(conn);
                st = Logica.sta(st);
                rs = Logica.Enlrepuesto(rs);
                String nom,des,pre,st;
                nom = txtnrep.getText();
                des = txtdes.getText();
                pre = txtpre.getText();
                st = txtst.getText();

                PreparedStatement graba = conn.prepareStatement("{call graba_repuesto(?,?,?,?)}");

                graba.setString(1, nom);
                graba.setString(2, des);
                graba.setString(3, pre);
                graba.setString(4, st);

                graba.executeUpdate();
                JOptionPane.showMessageDialog(null, "Repuesto registrado con Exito");
                conn.close();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error en BD" + e.toString());
            }
        }
    }//GEN-LAST:event_grabrepActionPerformed

    private void btncancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelar2ActionPerformed

    private void editrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editrepActionPerformed
        // TODO add your handling code here:
        int resp;
        resp=JOptionPane.showConfirmDialog(null,"¿Desea Modificar los Datos?","Pregunta", 0);
        if (resp==0) {
            try {
                conn=Logica.Enlace(conn);
                st=Logica.sta(st);
                rs=Logica.Enlrepuesto(rs);

                String  nom,des,pre,st;

                nom=txtnrep.getText();
                des=txtdes.getText();
                pre=txtpre.getText();
                st=txtst.getText();

                PreparedStatement modifica=conn.prepareStatement("{call edita_rep(?,?,?,?)}");

                modifica.setString(1,nom);
                modifica.setString(2, des);
                modifica.setString(3, pre);
                modifica.setString(4, st);

                modifica.executeUpdate();
                JOptionPane.showMessageDialog(null, "Datos modificados con Exito");
                conn.close();

            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null,"Error en BD"+ e.toString());
            }}
    }//GEN-LAST:event_editrepActionPerformed

    private void btngrabarrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarrepActionPerformed
        // TODO add your handling code here:
        int resp;
        boolean haygrabacion=false;
        resp=JOptionPane.showConfirmDialog(null,"¿Desea Grabar la venta actual?","Pregunta",0);
        if(resp==0) {
            try {
                conn=Logica.Enlace(conn);
                st=Logica.sta(st);
                rs=Logica.Enlrepuesto(rs);

                String cli,nom,can,tot,com,hor,fec;
                int cod,codcli=0,codnom=0;

                cli=(String)cboclienterep.getSelectedItem();
                rs1=Logica.ObtenerCodcliente(rs1, cli);
                if(rs1.next()) {
                    codcli=Integer.parseInt((String)rs1.getString(1));
                    haygrabacion=true;
                } else {
                    JOptionPane.showMessageDialog(null,"Seleccione un Cliente");
                    haygrabacion=false;
                }

                nom=(String)cborep.getSelectedItem();
                rs2=Logica.ObtenerCodRepuesto(rs2, nom);
                if(rs2.next()) {
                    codnom=Integer.parseInt((String)rs2.getString(1));
                    haygrabacion=true;
                } else {
                    JOptionPane.showMessageDialog(null,"Seleccione un producto");
                    haygrabacion=false;
                }


                com=(String)cboxcomprobante1.getSelectedItem();

                hor=lbhora.getText();
                fec=lbfecha.getText();
                can=txtcanrep.getText();
                tot=txttotrep.getText();



                
                                    if(can.equals("")){
                                        JOptionPane.showMessageDialog(null,"Ingrese una cantidad");
                                        txtcanrep.requestFocus();
                                    }else{

                                        if(tot.equals("")){
                                            JOptionPane.showMessageDialog(null,"Precio no calculado");
                                            txttotrep.requestFocus();
                                        }else{
                                            if(haygrabacion && !yaprogramado) {
                                                PreparedStatement graba=conn.prepareStatement("{call graba_ven(?,?,?,?,?,?,?)}");
                                                graba.setInt(1, codcli);
                                                graba.setInt(2, codnom);
                                                graba.setString(3, can);
                                                graba.setString(4, fec);
                                                graba.setString(5, hor);
                                                graba.setString(6, tot);
                                                graba.setString(7, com);
                                                
                                                graba.executeUpdate();
                                                JOptionPane.showMessageDialog(null,"Datos de venta registrados con éxito");
                                                conn.close();
                                                //activabotones(true,false,false,false);
                                                //limpiar()
                                            }}}
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null,"Error en BD"+e.toString());
            }
        }
    }//GEN-LAST:event_btngrabarrepActionPerformed

    private void btncancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelar3ActionPerformed

    private void cborepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cborepActionPerformed
        // TODO add your handling code here:
        String rep,inf="";

        try{
            int pre=0;
            rep=(String)cborep.getSelectedItem();
            rs=Logica.info(rs, rep);
            if(rs.next())
                inf=(String)rs.getString(1);
                pre=Integer.parseInt(rs.getString(2));
            lbinf.setText("Descripción:"+ inf);
            lbprerep.setText("Precio único:"+ String.valueOf(pre));
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(null,"Error en BD"+e.toString());
        }
    }//GEN-LAST:event_cborepActionPerformed

    private void totrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totrepActionPerformed
        // TODO add your handling code here:
        String rep;

        try{
            String res;
            int total,a,b,pre=0;
            rep=(String)cborep.getSelectedItem();
            rs4=Logica.preciopro(rs4, rep);
            if(rs4.next())
                pre=Integer.parseInt(rs4.getString(1));

            a=Integer.parseInt(txtcanrep.getText());
            total=a * pre;
            res=String.valueOf(total);
            txttotrep.setText(res);
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(null,"Error en BD"+e.toString());
        }
    }//GEN-LAST:event_totrepActionPerformed

    private void cboxcomprobante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxcomprobante1ActionPerformed
        // TODO add your handling code here:
           String compara;

            compara=(String)cboxcomprobante1.getSelectedItem();
            if(compara.equals("Boleta")){
                txtruc1.setVisible(false);
                lbruc1.setVisible(false);
            }
            if(compara.equals("Factura")){
                txtruc1.setVisible(true);
                lbruc1.setVisible(true);
                txtruc1.requestFocus();

            }
            if(compara.equals("Seleccionar")){
                txtruc1.setVisible(false);
                lbruc1.setVisible(false);
            }
    }//GEN-LAST:event_cboxcomprobante1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        vrep.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        repuestos.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        rep_cliente.visualiza();
    }//GEN-LAST:event_jMenuItem7ActionPerformed



    // venta de repuesto

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame auto;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnagregar1;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncancelar1;
    private javax.swing.JButton btncancelar2;
    private javax.swing.JButton btncancelar3;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btngrabar1;
    private javax.swing.JButton btngrabarrep;
    private javax.swing.JButton btnmodelo1;
    private javax.swing.JButton btnver;
    private javax.swing.JButton busrep;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbocliente;
    private javax.swing.JComboBox cboclienterep;
    private javax.swing.JComboBox cbocolor;
    private javax.swing.JComboBox cbomarca;
    private javax.swing.JComboBox cbomodelo;
    private javax.swing.JComboBox cborep;
    private javax.swing.JComboBox cbotipo;
    private javax.swing.JComboBox cboxcomprobante;
    private javax.swing.JComboBox cboxcomprobante1;
    private javax.swing.JInternalFrame cliente;
    private javax.swing.JButton editrep;
    private javax.swing.JButton grabrep;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbfecha;
    private javax.swing.JLabel lbhora;
    private javax.swing.JLabel lbinf;
    private javax.swing.JLabel lbprecio;
    private javax.swing.JLabel lbprerep;
    private javax.swing.JLabel lbruc;
    private javax.swing.JLabel lbruc1;
    private javax.swing.JLabel lbtotal;
    private javax.swing.JInternalFrame repuestos;
    private javax.swing.JTable tbcliente;
    private javax.swing.JTable tbrep;
    private javax.swing.JButton totrep;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcan;
    private javax.swing.JTextField txtcanrep;
    private javax.swing.JTextArea txtdes;
    private javax.swing.JTextField txtdir;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnrep;
    private javax.swing.JTextField txtpre;
    private javax.swing.JTextField txtruc;
    private javax.swing.JTextField txtruc1;
    private javax.swing.JTextField txtst;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField txttotrep;
    private javax.swing.JButton verrep;
    private javax.swing.JInternalFrame vrep;
    // End of variables declaration//GEN-END:variables

}
